### PR TITLE
adds asynchronous load of the extension

### PR DESCRIPTION
**Pull request by noreflection**
This pull request adds an asynchronous load of the extension so it could work properly in VS2019 without throwing notification. In order to make async load possible, Microsoft.VisualStudio.Shell.15 package has been added and the project .csproj was updated to target 4.7.2

### CODE REVIEW

**Review by justcla — COMMENTED** [review]
Thanks Nikita. Looks good.

One question: why did you add the imaging library? Was it brought in as a dependency of the Shell.15 package?

**Comment by noreflection** [comment]
yes, it happens to be one of [Microsoft.VisualStudio.Shell.15.0](https://www.nuget.org/packages/Microsoft.VisualStudio.Shell.15.0) dependency package. 
I forgot to mention that I also had to manually remove previous Shell.12 and Microsoft.VisualStudio.Shell.Immutable.10.0 packages from the references since they have some naming collisions with Shell.15 and Microsoft.VisualStudio.Framework (which was also brought as one of Shell.15 dependencies) respectively.

**Comment by justcla** [comment]
Thanks.
So does this mean it won't run in VS 2015 any more?

**Comment by noreflection** [comment]
I just installed VS2015 Community and installed the updated extension from this pr branch on it and sadly it's not working in VS2015. It shows modal with error message and link to an xml log file. Inside this file I see one of the row saying: "Could not load file or assembly: Microsoft.VisualStudio.Shell.15.0". Not sure why it's happening...

**Comment by justcla** [comment]
Shell.15 is only available from VS2017 and above.
That's one of the downsides of the AsyncPackage stuff.
It just means we'll need to separate out the existing version and keep it as a legacy download. Or we create a new Guid for this one and make it VS2017+.

**Comment by noreflection** [comment]
yeah, it seems like that. Do you want me to generate new guid for this extension in this pr? 

and I suppose we need to update current:
InstallationTarget Id="Microsoft.VisualStudio.IntegratedShell" Version="[11.0,]" /> 
to:
InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0,)" /> 

in .vsixmanifest to indicate that this version is only available from VS2017+. Should I do this in current pr?

**Comment by justcla** [comment]
Tough call. Many users have already installed it for VS2019. If we use the same Guid, those users will get an automatic upgrade, which is probably the best thing for us to do for them.

Although, users on VS2015 will get a rude shock when they upgrade, as it will simply stop writing for them.

I think we should keep the same Guid for VS2109 and create a new Guid for the legacy one. I'll sort that out.

Let's make the installation target for this one VS2017+.
If you could do that, I'd be grateful. Thanks!

**Comment by noreflection** [comment]
sounds reasonable.
I've updated .vsixmanifest so now it only offers to install it on VS2017/2019 skipping 2015.
Justin, thank you very much for supporting this great extension!

**Comment by justcla** [comment]
I have released a new version for VS2017/VS2019 with a new GUID.
It's available on the marketplace here: [Emacs Emulation 2](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.EmacsEmulation2&ssr=false#overview)

**Pull request merged**
