### PR TITLE
VS2019 support

### PR DESCRIPTION
**Pull request by lalmstrom**

### CODE REVIEW

**Comment by DamienCassou** [comment]
The current release can't be installed on VS2019. If this PR fixes the problem, could you please merge it and release again @justcla?

**Comment by Morozov-5F** [comment]
@DamienCassou it looks like this repo is abandoned. Maybe it'd be good to release your fork to VS marketplace?

**Comment by justcla** [comment]
Sorry for the late response.
I've been flat out with some other stuff.
I'm planning to upgrade all my extensions in two weeks.
But I'm happy to push this one to the marketplace if someone can provide the VSIX.
(With updated version and release notes)
Thanks!

**Comment by tessiof** [comment]
Any update on this?

**Comment by justcla** [comment]
Sorry, no. Still waiting to get an install of VS2019. If someone else upgrades it, I can upload it to the Marketplace.

**Comment by justcla** [comment]
I have VS 2019 installed! Will update the extension soon.

**Comment by justcla** [comment]
This PR does not address the AutoLoad issues. I'm now seeing this message when it loads in VS2019.
image

**Comment by justcla** [comment]
I'm going to accept the PR anyway and publish the extension to the Marketplace.
Hopefully someone will fix the [AutoLoad issue](https://github.com/justcla/EmacsKeys/blob/master/EmacsEmulationPackage.cs#L40).
:-D

**Comment by justcla** [comment]
Latest version is now available on the [Visual Studio Martketplace](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.EmacsEmulation)

Previous versions available in [Releases](https://github.com/justcla/EmacsKeys/releases).

**Pull request merged**
